spring.application.name=cloud-store
server.port=8080
server.tomcat.connection-timeout=10000
spring.jpa.open-in-view=false
server.shutdown=graceful
logging.level.org.springframework=INFO
logging.level.com.samson.cloudstore=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId}] [user:%X{username}:%X{userId}] %logger{36} - %msg%n

# =========================
# Database Configs (PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://postgresqlserverdb.postgres.database.azure.com:5432/postgres
# spring.datasource.url=jdbc:postgresql://localhost:5432/cloud-store-db
spring.datasource.username=samson
spring.datasource.password=Hbwv_6273
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# =========================
# Flyway Miscellaneous Configs
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true

# =========================
# Resilience4j Configs
# =========================
resilience4j.circuitbreaker.instances.users.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.users.sliding-window-size=20
resilience4j.circuitbreaker.instances.users.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.users.wait-duration-in-open-state=50s

# =========================
# JWT & Security Settings
# =========================
app.jwt.issuer=samson-backend

jwt.rotating-keys.issuer=samson-backend
jwt.rotating-keys.current-key-id=k1
jwt.rotating-keys.access-ttl=15m
jwt.rotating-keys.refresh-ttl=7d

jwt.rotating-keys.key-specification-list[0].key-id=k1
jwt.rotating-keys.key-specification-list[0].secret-base64=YXNnONz14eXKalXe5uis3ks178yxgL592ZbmYKnlZ4s

# Optional: add a second key (for rotation)
jwt.rotating-keys.key-specification-list[1].key-id=k2
jwt.rotating-keys.key-specification-list[1].secret-base64=nMwPAY0c8iMjnbJMrfokaOd5aXn_cCFzEZUNVg0cLM0

app.storage.bucket=cloudstore-user-files
app.storage.max-file-size-bytes=10737418240

app.minio.endpoint=http://192.168.50.17:9000

# Todo: change this
app.minio.access-key=cloudadmin
app.minio.secret-key=hbwv6273

spring.jpa.properties.hibernate.jdbc.type.preferred_enum_jdbc_type=VARCHAR
app.cors.allowed-origins[0]=http://localhost:3000
app.cors.allowed-origins[1]=http://192.168.50.153:3000
app.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.storage.trash-retention-days=30
app.storage.presign-ttl=15m
app.storage.multipart.part-size-bytes=8388608
app.storage.user-quota-bytes=107374182400

